// apps/website/recipes/direct/Recipe.svelte
<script lang="ts">
import { bindClient } from "spinetab/svelte";
import { spinetab } from "./live";
import { queueSource, selectQueue } from "./source";

const { liveStore } = bindClient(spinetab);
const queue = liveStore(queueSource, { map: selectQueue, reconcile: "latest" });
</script>

{#if $queue.error || $queue.data?.problem}
	<p role="alert">{$queue.error?.message ?? $queue.data?.problem}</p>
{:else if $queue.data?.open === undefined}
	<p role="status">Loading queue…</p>
{:else}
	<p><output>{$queue.data.open}</output> open</p>
{/if}

// apps/website/recipes/direct/Recipe.vue
<script setup lang="ts">
import { bindClient } from "spinetab/vue";
import { spinetab } from "./live";
import { queueSource, selectQueue } from "./source";

const { useLive } = bindClient(spinetab);
const { data, error } = useLive(queueSource, {
	map: selectQueue,
	reconcile: "latest",
});
</script>

<template>
	<p v-if="error || data?.problem" role="alert">
		{{ error?.message ?? data?.problem }}
	</p>
	<p v-else-if="data?.open === undefined" role="status">Loading queue…</p>
	<p v-else><output>{{ data.open }}</output> open</p>
</template>
