// apps/website/recipes/direct/Recipe.solid.tsx
import { bindClient } from "spinetab/solid";
import { spinetab } from "./live";
import { queueSource, selectQueue } from "./source";

const { createLive } = bindClient(spinetab);

export default function Recipe() {
	const queue = createLive(queueSource, {
		map: selectQueue,
		reconcile: "latest",
	});
	const problem = () => queue.error()?.message ?? queue.data()?.problem;
	return (
		<>
			{problem() ? (
				<p role="alert">{problem()}</p>
			) : queue.data()?.open === undefined ? (
				<p role="status">Loading queue…</p>
			) : (
				<p>
					<output>{queue.data()?.open}</output> open
				</p>
			)}
		</>
	);
}

// apps/website/recipes/direct/Recipe.svelte
<script lang="ts">
import { bindClient } from "spinetab/svelte";
import { spinetab } from "./live";
import { queueSource, selectQueue } from "./source";

const { liveStore } = bindClient(spinetab);
const queue = liveStore(queueSource, { map: selectQueue, reconcile: "latest" });
</script>

{#if $queue.error || $queue.data?.problem}
	<p role="alert">{$queue.error?.message ?? $queue.data?.problem}</p>
{:else if $queue.data?.open === undefined}
	<p role="status">Loading queue…</p>
{:else}
	<p><output>{$queue.data.open}</output> open</p>
{/if}
