// apps/website/recipes/ai/Recipe.tsx
import { useChat } from "@ai-sdk/react";
import { useEffect, useState } from "react";
import { chatId, transport } from "./transport";

export default function Recipe() {
	const [mounted, setMounted] = useState(false);
	const { messages, status, error, sendMessage, resumeStream, stop } = useChat({
		id: chatId,
		transport,
	});
	useEffect(() => {
		setMounted(true);
		const unfollow = transport.follow(chatId, resumeStream);
		void resumeStream();
		return () => {
			unfollow();
			void stop();
		};
	}, [resumeStream, stop]);
	const busy = status === "submitted" || status === "streaming";
	return (
		<section aria-label="Chat">
			{messages.map((message) => (
				<p key={message.id}>
					{message.parts
						.map((part) => (part.type === "text" ? part.text : ""))
						.join("")}
				</p>
			))}
			{error && <p role="alert">{error.message}</p>}
			<p role="status">{status}</p>
			<button
				type="button"
				disabled={!mounted || busy}
				onClick={() => {
					void sendMessage({
						text: "Explain shared browser connections in one sentence.",
					});
				}}
			>
				Send
			</button>
		</section>
	);
}

// apps/website/recipes/ai/Recipe.svelte
<script lang="ts">
import { Chat } from "@ai-sdk/svelte";
import { onMount } from "svelte";
import { chatId, transport } from "./transport";

const chat = new Chat({ id: chatId, transport });
let mounted = $state(false);
const busy = $derived(
	chat.status === "submitted" || chat.status === "streaming",
);
onMount(() => {
	mounted = true;
	const resume = () => chat.resumeStream();
	const unfollow = transport.follow(chatId, resume);
	void resume();
	return () => {
		unfollow();
		void chat.stop();
	};
});
</script>

<section aria-label="Chat">
	{#each chat.messages as message (message.id)}
		<p>
			{message.parts.map((part) => part.type === "text" ? part.text : "").join("")}
		</p>
	{/each}
	{#if chat.error}
		<p role="alert">{chat.error.message}</p>
	{/if}
	<p role="status">{chat.status}</p>
	<button
		type="button"
		disabled={!mounted || busy}
		onclick={() => { void chat.sendMessage({ text: "Explain shared browser connections in one sentence." }); }}
	>
		Send
	</button>
</section>
