// apps/website/recipes/query/Queue.tsx
import { skipToken, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { startQueue } from "./feed";
import type { QueueView } from "./queue-types";

export default function Queue() {
	const client = useQueryClient();
	const { data } = useQuery<QueueView>({
		queryKey: ["queue"],
		queryFn: skipToken,
	});
	const [error, setError] = useState("");
	useEffect(() => {
		const binding = startQueue(client, setError);
		return () => binding.unsubscribe();
	}, [client]);
	if (error || data?.problem)
		return <p role="alert">{error || data?.problem}</p>;
	if (data?.open === undefined) return <p role="status">Loading queue…</p>;
	return (
		<p>
			<output>{data.open}</output> open
		</p>
	);
}

// apps/website/recipes/query/Queue.svelte
<script lang="ts">
import { createQuery, skipToken, useQueryClient } from "@tanstack/svelte-query";
import { onMount } from "svelte";
import { startQueue } from "./feed";
import type { QueueView } from "./queue-types";

const client = useQueryClient();
const queue = createQuery<QueueView>(() => ({
	queryKey: ["queue"],
	queryFn: skipToken,
}));
let error = $state("");
onMount(() => {
	const binding = startQueue(client, (message) => {
		error = message;
	});
	return () => binding.unsubscribe();
});
</script>

{#if error || queue.data?.problem}
	<p role="alert">{error || queue.data?.problem}</p>
{:else if queue.data?.open === undefined}
	<p role="status">Loading queue…</p>
{:else}
	<p><output>{queue.data.open}</output> open</p>
{/if}
