// apps/website/recipes/query/Queue.svelte
<script lang="ts">
import { createQuery, skipToken, useQueryClient } from "@tanstack/svelte-query";
import { onMount } from "svelte";
import { startQueue } from "./feed";
import type { QueueView } from "./queue-types";

const client = useQueryClient();
const queue = createQuery<QueueView>(() => ({
	queryKey: ["queue"],
	queryFn: skipToken,
}));
let error = $state("");
onMount(() => {
	const binding = startQueue(client, (message) => {
		error = message;
	});
	return () => binding.unsubscribe();
});
</script>

{#if error || queue.data?.problem}
	<p role="alert">{error || queue.data?.problem}</p>
{:else if queue.data?.open === undefined}
	<p role="status">Loading queue…</p>
{:else}
	<p><output>{queue.data.open}</output> open</p>
{/if}

// apps/website/recipes/query/Queue.solid.tsx
import { createQuery, skipToken, useQueryClient } from "@tanstack/solid-query";
import { createSignal, onCleanup, onMount } from "solid-js";
import { startQueue } from "./feed";
import type { QueueView } from "./queue-types";

export default function Queue() {
	const client = useQueryClient();
	const queue = createQuery<QueueView>(() => ({
		queryKey: ["queue"],
		queryFn: skipToken,
	}));
	const [error, setError] = createSignal("");
	let binding: ReturnType<typeof startQueue> | undefined;
	onMount(() => {
		binding = startQueue(client, setError);
	});
	onCleanup(() => binding?.unsubscribe());
	const problem = () => error() || queue.data?.problem;
	return (
		<>
			{problem() ? (
				<p role="alert">{problem()}</p>
			) : queue.data?.open === undefined ? (
				<p role="status">Loading queue…</p>
			) : (
				<p>
					<output>{queue.data.open}</output> open
				</p>
			)}
		</>
	);
}
