// apps/website/recipes/trpc/Recipe.svelte
<script lang="ts">
import { onMount } from "svelte";
import type { QueueView } from "./queue-types";
import { watchQueue } from "./watch";

let data = $state<QueueView>();
let error = $state("");
onMount(() =>
	watchQueue(
		(value) => {
			data = value;
			error = "";
		},
		(message) => {
			error = message;
		},
	),
);
</script>

{#if error}
	<p role="alert">{error}</p>
{:else if data?.open === undefined}
	<p role="status">Loading queue…</p>
{:else}
	<p><output>{data.open}</output> open</p>
{/if}

// apps/website/recipes/trpc/Recipe.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import type { QueueView } from "./queue-types";
import { watchQueue } from "./watch";

const data = ref<QueueView>();
const error = ref("");
let stop: (() => void) | undefined;
onMounted(() => {
	stop = watchQueue(
		(value) => {
			data.value = value;
			error.value = "";
		},
		(message) => {
			error.value = message;
		},
	);
});
onUnmounted(() => stop?.());
</script>

<template>
	<p v-if="error" role="alert">{{ error }}</p>
	<p v-else-if="data?.open === undefined" role="status">Loading queue…</p>
	<p v-else><output>{{ data.open }}</output> open</p>
</template>
