// apps/website/recipes/trpc/Recipe.solid.tsx
import { createSignal, onCleanup, onMount } from "solid-js";
import type { QueueView } from "./queue-types";
import { watchQueue } from "./watch";

export default function Recipe() {
	const [data, setData] = createSignal<QueueView>();
	const [error, setError] = createSignal("");
	let stop: (() => void) | undefined;
	onMount(() => {
		stop = watchQueue((value) => {
			setData(value);
			setError("");
		}, setError);
	});
	onCleanup(() => stop?.());
	return (
		<>
			{error() ? (
				<p role="alert">{error()}</p>
			) : data()?.open === undefined ? (
				<p role="status">Loading queue…</p>
			) : (
				<p>
					<output>{data()?.open}</output> open
				</p>
			)}
		</>
	);
}

// apps/website/recipes/trpc/Recipe.tsx
import { useEffect, useState } from "react";
import type { QueueView } from "./queue-types";
import { watchQueue } from "./watch";

export default function Recipe() {
	const [data, setData] = useState<QueueView>();
	const [error, setError] = useState("");
	useEffect(
		() =>
			watchQueue((value) => {
				setData(value);
				setError("");
			}, setError),
		[],
	);
	if (error) return <p role="alert">{error}</p>;
	if (data?.open === undefined) return <p role="status">Loading queue…</p>;
	return (
		<p>
			<output>{data.open}</output> open
		</p>
	);
}
